[package]
name = "nederlandskie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
atrium-api = "0.4.0"
atrium-xrpc = "0.3.0"
chrono = "0.4.26"
ciborium = "0.2.1"
futures = "0.3.28"
libipld-core = { version = "0.16.0", features = ["serde-codec"] }
rs-car = "0.4.1"
scooby = "0.4.0"
serde_ipld_dagcbor = "0.4.0"
sqlx = { version = "0.7.1", features = ["chrono"] }
tokio = { version = "1.32.0", features = ["full"] }
tokio-tungstenite = { version = "0.20.0", features = ["native-tls"] }
